### ISSUE TITLE
Docker image for new Apama version

### ISSUE THREAD

**Issue by tdalianis** [HEADS-project/ApamaComponents#2]
Hi,

Is there a docker version of the latest Apama version (9.10)? 
Can someone use predefined queries created in apama studio along with the kevorized components?

**Comment by skorsky** [comment]
Now the latest Apama version is 9.12.

There is no Docker version using the Apama 9.10 client libraries as the current content of this repository uses the client libraries of Apama 5.3. 

If you start the eu.heads.apama.ApamaSubscriber with some EPL text for the query parameter, you can run a query created in Apama Studio with the kevorized components. This way is not very comfortable since you use very long strings for the query parameter, which is far from being readable.

My preferred approach would be to export the Apama project and make it available to the Docker container and use the generated Ant scripts to start the correlator with the queries.

**Comment by maxleiko** [comment]
What's the status on that issue? Can we close it?

**Comment by skorsky** [comment]
To which docker registry should I deliver the image? It's about 800 MB.

**Comment by maxleiko** [comment]
The official one https://hub.docker.com
Check-out [this documentation](https://docs.docker.com/docker-hub/repos/)

**Comment by skorsky** [comment]
On the official docker registry use 
´docker pull martrain/apama´.
This is Apama version 9.12.0.1, the newest version as of today.
Use ´docker run -it martrain/apama bash´.
Map the folders with the license file and other files needed (e.g. the Apama project).
